# See https://github.com/FlyingPikachu/Quests/wiki/Configuration
language: en
allow-command-questing: true
allow-command-quests-with-npcs: false
show-requirements: true
show-titles: true
allow-quitting: true
use-compass: true
ignore-locked-quests: false
generate-files-on-join: true
kill-delay: 600
npc-effects:
  enabled: true
  new-quest: note
  redo-quest: angry_villager
max-quests: 0
convert-data-on-startup: false
quester-blacklist:
- UUID
- UUID
- UUID